### PR TITLE
Sample Logo for Edamontology

### PR DESCRIPTION
**Pull request by Tosin-Bakare**
This is a sample logo create by Tosin-Bakare for Edam Browser  Outreachy Project.

### CODE REVIEW

**Review by matuskalas — COMMENTED** [review]
Dear @Tosin-Bakare, thank you very much for your contribution, and for submitting your final application on time!

When I view your file, it looks a bit cut. This is how it looks for me:
image
Maybe something in your conversion?

Would you mind renaming the file to something like `EDAM-logo-Tosin.svg`? And creating a pull request in the central repository https://github.com/edamontology/logoi?

Million thanks🙏🏽

**Comment by Tosin-Bakare** [comment]
Dear @matuskalas I just uploaded a renamed version of the logo. Kindly check if it displays properly now and give a  feedback.   Cheers.

**Comment by matuskalas** [comment]
I see now, it was a problem how GitHub was (not) resizing the rendered image, so no problem!

Would you please create a pull request from your `main` branch to the central repo (`https://github.com/edamontology/logoi`), as GitHub suggests you (at https://github.com/Tosin-Bakare/logoi)? If it's only in your fork, nobody would have seen it (I only found it because you listed it in your contributions on the Outreachy website)

Then please rename also the logo with the blue background (you can do it also in the `main` branch) to something like `EDAM-logo-Tosin-Bakare2.svg`. Thanks!

**Comment by Tosin-Bakare** [comment]
Hello @matuskalas I just renamed the file and sent a pull request to the central repo. Cheers.

**Pull request merged**
